/*eslint-disable */
export const CURRENCIES = {
  'AED': {
    'symbol': 'AED',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'ARS': {
    'symbol': '$',
    'symbolFirst': true,
    'thousand': '.',
    'lowRate': false,
  },
  'AUD': {
    'symbol': 'A$',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'BDT': {
    'symbol': '৳',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'BHD': {
    'symbol': 'ب.د',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'BRL': {
    'symbol': 'R$',
    'symbolFirst': true,
    'thousand': '.',
    'lowRate': false,
  },
  'CAD': {
    'symbol': 'C$',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'CHF': {
    'symbol': 'Fr',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'CLP': {
    'symbol': 'CLP$',
    'symbolFirst': true,
    'thousand': '.',
    'lowRate': false,
  },
  'CNY': {
    'symbol': '¥',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'COP': {
    'symbol': 'COL$',
    'symbolFirst': true,
    'thousand': '.',
    'lowRate': true,
  },
  'DZD': {
    'symbol': 'DZD',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'EGP': {
    'symbol': 'EGP',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'EUR': {
    'symbol': '€',
    'symbolFirst': false,
    'thousand': ' ',
    'lowRate': false,
  },
  'GBP': {
    'symbol': '£',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'GHS': {
    'symbol': '₵',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'HKD': {
    'symbol': 'HK$',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'IDR': {
    'symbol': 'Rp',
    'symbolFirst': true,
    'thousand': '.',
    'lowRate': true,
  },
  'ILS': {
    'symbol': '₪',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'INR': {
    'symbol': '₹',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'JOD': {
    'symbol': 'د.ا',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'JPY': {
    'symbol': '¥',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'KRW': {
    'symbol': '₩',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': true,
  },
  'KWD': {
    'symbol': 'د.ك',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'LKR': {
    'symbol': '₨',
    'symbolFirst': false,
    'thousand': ',',
    'lowRate': false,
  },
  'MAD': {
    'symbol': 'MAD',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'MOP': {
    'symbol': 'P',
    'symbolFirst': false,
    'thousand': ',',
    'lowRate': false,
  },
  'MXN': {
    'symbol': 'MEX$',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'MYR': {
    'symbol': 'RM',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'NGN': {
    'symbol': '₦',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'NZD': {
    'symbol': 'NZ$',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'OMR': {
    'symbol': 'ر.ع.',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'PHP': {
    'symbol': '₱',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'PKR': {
    'symbol': '₨',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'PLN': {
    'symbol': 'zł',
    'symbolFirst': false,
    'thousand': ' ',
    'lowRate': false,
  },
  'QAR': {
    'symbol': 'ر.ق',
    'symbolFirst': false,
    'thousand': ',',
    'lowRate': false,
  },
  'RUB': {
    'symbol': '₽',
    'symbolFirst': false,
    'thousand': ' ',
    'lowRate': false,
  },
  'SAR': {
    'symbol': 'SAR',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'SEK': {
    'symbol': 'kr',
    'symbolFirst': false,
    'thousand': ' ',
    'lowRate': false,
  },
  'SGD': {
    'symbol': 'S$',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'THB': {
    'symbol': '฿',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'TND': {
    'symbol': 'TND',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'TRY': {
    'symbol': '₺',
    'symbolFirst': true,
    'thousand': '.',
    'lowRate': false,
  },
  'TWD': {
    'symbol': 'NT$',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'USD': {
    'symbol': 'US$',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
  'VND': {
    'symbol': '₫',
    'symbolFirst': false,
    'thousand': '.',
    'lowRate': true,
  },
  'ZAR': {
    'symbol': 'R',
    'symbolFirst': true,
    'thousand': ',',
    'lowRate': false,
  },
};
/*eslint-enable */
